name: codelabs_builder
description: Command-line application for codelabs.

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  build_cli_annotations: ^2.1.0
  collection: ^1.18.0
  html: ^0.15.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  markdown: ^7.1.1
  path: ^1.9.0
  quiver: ^3.2.1
  yaml: ^3.1.2

dev_dependencies:
  build_cli: ^2.2.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  pedantic: ^1.11.1
  lints: ^2.1.0
  test: ^1.24.0
  coverage: ^1.7.2

